services:
    frontend_html:
        build: ./frontend_v3/html
        container_name: frontend_html
        restart: always
        ports:
            - "5173:80"
        volumes:
            - ./frontend_v3/html/site:/usr/share/nginx/html/
            - ./frontend_v3/html:/app/
    frontend_manager:
        build: ./frontend_v3/manager
        container_name: frontend_manager
        restart: always
        volumes:
            - ./frontend_v3:/app
        ports:
            - "5174:5174"
    frontend_devtodo:
        build: ./frontend_v3/devtodo
        container_name: frontend_devtodo
        restart: always
        volumes:
            - ./frontend_v3:/app
        ports:
            - "5175:5175"
    backend_todos:
        build: ./backend/todos
        container_name: backend_todos
        restart: always
        volumes:
            - ./backend/todos:/app
            - ./data:/app/data
        ports:
            - "3010:3000"
