services:
    frontend_html:
        build: ./frontend_v3/html
        container_name: frontend
        restart: always
        ports:
            - "5173:80"
        volumes:
            - ./frontend_v3/html/site:/usr/share/nginx/html/
    frontend_manager:
        build: ./frontend_v3/manager
        container_name: frontend_manager
        restart: always
        volumes:
            - ./frontend_v3:/app
        ports:
            - "5174:5173"
