- name: reachability check
  hosts: web
  gather_facts: no
  tasks:
      - name: Ausgabe Hostname zur Kontrolle
        debug:
            msg: "Überprüfe Verbindung zu {{ inventory_hostname }}"

      - name: Wait until host is reachable via SSH (max 5 Versuche, 10 Sekunden Abstand)
        wait_for_connection:
            delay: 5
            timeout: 30 # etwas kürzer, zum Testen
        register: result
        until: result is success
        retries: 3
        delay: 5
      - name: Ping-Check (funktioniert nur wenn Ansible Verbindung klappt)
        ping:
