---
- name: Run command in specific path on remote server
  hosts: web
  vars:
      path: "" # z.B. /opt/app
      command: "" # z.B. npm install

  tasks:
      - name: Print working directory
        debug:
            msg: "Working directory is: {{ path }}"

      - name: Print command to run
        debug:
            msg: "Command to execute is: {{ command }}"

      - name: Run custom command in specific path
        shell: "{{ command }}"
        args:
            chdir: "{{ path }}"
